steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'YOUR_SERVICE_NAME'
      - '--image=gcr.io/$PROJECT_ID/$REPO_NAME'
      - '--region=YOUR_REGION'
      - '--platform=managed'

options:
  logging: CLOUD_LOGGING_ONLY