steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
    id: 'push-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=.'
      - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - '--location=us-central1'
      - '--output=/workspace/output'
    id: 'deploy-cloudrun'

  # Step 4: Deploy to Cloud Run using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    id: 'deploy'

# Substitutions (can be overridden at build time)
substitutions:
  _SERVICE_NAME: 'mysite'
  _REGION: 'us-central1'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed to registry
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'

# Timeout for the build
timeout: '1800s'
