steps:
  # Step 1: Build the image using Google Cloud Buildpacks (auto-detect Node/Vite)
  - name: 'gcr.io/buildpacks/builder:v1'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - '.'
    id: 'build-image'

  # Step 2: Deploy to Cloud Run using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    id: 'deploy'

# Substitutions (can be overridden at build time)
substitutions:
  _SERVICE_NAME: 'mysite'
  _REGION: 'us-central1'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed to registry
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'

# Timeout for the build
timeout: '1200s'
